### ISSUE TITLE
Wie kann ich erkennen, dass der PDF-Indexer funktioniert?

### ISSUE THREAD

**Issue by math-GH** [heimrichhannot/contao-search-bundle#1]
Wie kann ich erkennen, dass der PDF-Indexer funktioniert?

- In Contao 4.9 habe ich dieses Bundle installiert.

- smalot/pdfparser ist per composer.json installiert worden
![grafik](https://user-images.githubusercontent.com/1645099/103150275-d593a900-4772-11eb-9a06-0aa3fa00cf24.png)

- config/config.yml habe ich die Einstellungen eingetragen
![grafik](https://user-images.githubusercontent.com/1645099/103150282-eba16980-4772-11eb-9cf1-25bc7fc9994d.png)

- Prod-Cache im Contao Manager wurde aktualisiert

- eine PDF stelle ich per Download-Modul im Frontend bereit

jedoch finde ich über die Search Engine die Inhalte der PDF nicht (das Wort "Navigation" kommt u.a. darin vor).

Was triggert die indizierung der PDF-Dateien?

**Comment by koertho** [comment]
Hast du den Search Index neu aufgebaut?

**Comment by math-GH** [comment]
ja, Suchindex habe ich mehrfach neu aufgabaut

![grafik](https://user-images.githubusercontent.com/1645099/103159350-b9225b80-47c8-11eb-9266-6a1d1f753b86.png)


Das Suchlog funktioniert jedoch korrekt und schreibt die Eingaben in die Logdatei. Also ist die Erweiterung und die Yaml korrekt eingestellt.

**Comment by koertho** [comment]
Puh, also noch zwei Ideen:
- Dateigröße zu groß
- PDF-Datei-Text kann ist nicht lesbar (bspw. Weil Bild statt Text)

Ansonsten bin ich über den Jahreswechsel nicht im Büro, könnte technische Probleme erst nächstes Jahr lösen. Eventuell kannst du dich ja Mal selbst durchdebuggen.

**Comment by math-GH** [comment]
Ich habe mehrere PDFs hinterlegt
![grafik](https://user-images.githubusercontent.com/1645099/103245484-9b87fa00-4960-11eb-86c0-e3879c5a2cc4.png)

darin ist jeweils Text vorhanden.

In der tl_seach_index ist nichts davon zu finden.

Eine Lösung eilt bei mir nicht. Mach dir bitte einen entspannten Jahrewechsel.

**Comment by koertho** [comment]
Hallo, ich bin heute dazu gekommen, es nochmal zu testen. Habe auch deine Einstellungen so übernommen. Die PDFs werden problemlos indexiert. Hast du unter _Systemwartung -> Crawler -> Den Suchindex aktualisieren_ ausgeführt?

**Comment by math-GH** [comment]
> Hallo, ich bin heute dazu gekommen, es nochmal zu testen. Habe auch deine Einstellungen so übernommen. Die PDFs werden problemlos indexiert. Hast du unter _Systemwartung -> Crawler -> Den Suchindex aktualisieren_ ausgeführt?

ja, hatte ich.

Wie könnte ich das am geschicktesten debuggen, damit ich rausfinde, an welcher Stelle es klemmen könnte?

**Comment by koertho** [comment]
Ok, weil der Screenshot, den du geschickt hast, nur das leeren der Tabelle zeigt.

Wenn du Xdebug hast, könntest du schauen, ob er hier rein geht: https://github.com/heimrichhannot/contao-search-bundle/blob/1cf32a070c323b29a98a785c59454fe6f482c39e/src/Indexer/PdfSearchIndexer.php#L100 (und dann durchdebuggen ob er irgendwo raus fliegt).
Notfalls tut es auch ein die(), aber der Crawler läuft ja asynchron, da müsstest du dir dann die Rückgabe anschauen.

**Comment by rorych** [comment]
Hatte das gleiche Problem. Mit dem Symfony-Profiler habe ich gesehen, dass im Plugin Smalot\PdfParser ein Fehler geworfen wurde, dieser Beitrag hat das Problem bei mir dann gelöst:
https://stackoverflow.com/questions/64532610/call-to-undefined-method-smalot-pdfparser-encoding-tostring

Dies wurde auch durch den Entwickler selbst gelöst, aber erst in der Version: 0.18.2
https://github.com/smalot/pdfparser/commit/b6db6aa9f605e9a82a29f1325309929a1e0beac0#diff-27bc594b24bd5e2779e8d81ee79810d0ffda03f200f0d53be007a44a9d2cb2de

Sprich schaut, dass Ihr mind. die 0.18.2 von smalot/pdfparser habt.

**Comment by koertho** [comment]
@rorych Danke für die Info. Bei uns ist das Problem tatsächlich nicht aufgetreten, kommt eventuell auf die PDF-Dateien an. Ich werde aber mal die minimal-Version hochdrehen, damit der Fehler nicht mehr auftritt.
