### ISSUE TITLE
Error SQL, wenn 1 Zeichen gesucht wird

### ISSUE THREAD

**Issue by math-GH** [heimrichhannot/contao-search-bundle#2]
Contao 4.9

Systemlog:
![grafik](https://user-images.githubusercontent.com/1645099/103159412-71500400-47c9-11eb-86c7-2bd7cf1dfb1d.png)

Gesucht habe ich nach "a"
![grafik](https://user-images.githubusercontent.com/1645099/103159435-a78d8380-47c9-11eb-87d9-70b91440a522.png)

aber auch "ab", "abc" werfen diesen Fehler. "abcd" wirft kein Fehler. Liegt vielleicht daran, dass mindestens 4 Zeichen eingegeben werden müssen

**Comment by koertho** [comment]
Anhand des Fehler kann ich nicht erkennen, warum der Fehler bei uns liegen sollte. Wir bauen den Search Query ja nicht zusammen.

**Comment by math-GH** [comment]
oh. Jetzt sehe ich es: In einer Installation ohne diese Erweiterung tritt dieser Fehler auch auf.
Es ist also ein Contao-Fehler.
