### ISSUE TITLE
Installation fails under C4.13 and PHP 8.1

### ISSUE THREAD

**Issue by con2net** [heimrichhannot/contao-search-bundle#6]
I have a current system with C4.13.12 and PHP 8.1.10 and would like to install this extension (current version 2.7.2) via the Contao Manager (1.6.1).

Unfortunately, I get this error message and the installation is not possible.

`In InitCommand.php line 939:
                                                                               
  Package heimrichhannot/contao-search-bundle has requirements incompatible with your PHP version, PHP extensions and Composer version:
    - heimrichhannot/contao-search-bundle 2.7.2 requires php ^7.1 which does not match your installed version 8.1.10. 
`
Eh? Do I have an installation error or is there perhaps a bug?

Thank you!!

**Comment by koertho** [comment]
Hi, no, it is just not yet released for php 8. I will try to do it this week, but can't promise it :)

**Comment by con2net** [comment]
Thank you very much for taking care about this!

**Comment by koertho** [comment]
Should be fixed in 2.8.0
