### ISSUE TITLE
bad URLs with PDF-Search and Search-index-crawler

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-search-bundle#7]
**Context**
Contao version: 4.9.39
Bundle version: 2.8.1
PHP version: 7.4

**Description**
PDF-Search:

The URIs of the indexed PDF files captured by the search-index-crawler are displayed in the search results as follows:
`https:domain.tld/contao?act=crawl&crawl_subscriber_names[0]=search-index&do=maintenance&jobId=ca40c357-a608-4aeb-852d-4398908e5c94&ref=3xZ2ejhN&amp;file=files/path/to/filename.pdf`
Of course, this doesn't work in the frontend.
The correct URI would be `https:domain.tld/files/path/to/filename.pdf.`

**Comment by koertho** [comment]
Thanks for reporting. I could reproduce this behavior and will have a look into it.

**Comment by koertho** [comment]
@rustykowski Can you test if #8 fix you problem?

**Comment by rustykowski** [comment]
which version should i require for testing?

**Comment by rustykowski** [comment]
Your changes were successful. I downloaded the branch fix/7. The crawler-generated urls are valid now.

**Comment by koertho** [comment]
Fixed in 2.8.3

**Comment by rustykowski** [comment]
Great! Thank you, @koertho !
